Filtered input from duplicate city names;
anicmarko9/zadatak pull request #1
Opened 2022-12-14 00:10 UTC by anicmarko9

Izbacio sam duplikate za ime gradova u backendu, tako da poziva openweather API samo jednom umesto vise puta -> "Nis, Nis, Nis, Nis" -> "Nis";

Dodao sam ikone, tj. slike

Na server dodao uncaught i unhandled rejections, u app.ts dodao cors() helmet() i rateLimit()

Na front sredio UI dizajn, dodao komponentu Tables
Dodao metodu za prikazivanje ikona

Error handling u vezi Unique Keys, kao i kad je server offline

Dodao sve tipove u typescript

2022-12-15 21:19 UTC, anicmarko9 commented
Feature: Klikne se na naziv grada, ili se ukuca URL ->
localhost:3000/weathers/au
localhost:3000/weathers/br
...
Za sad sam omogucio drzave koje se nalaze u tabeli.

Nova ruta fetch-uje sa backenda podatke o drzave pomocu dvo-karakternog koda, pa iskoristi atribut "capitalCity" da nakon toga sinhronosno fetch-uje sa backenda podatke o glavnom gradu drzave i prikaze prosecnu temperaturu u prilogu.

2022-12-16 11:11 UTC, antonic901 commented on Final/backend/app.ts
> +app.use(cors());
Vidi ovog cors-a da koristis ugradjeno hendlovanje u Express-u. Imas primer kod mene kako sam to radio.

2022-12-16 12:07 UTC, antonic901 approved these changes

2022-12-23 12:34 UTC, antonic901 reviewed
Pogledaj da malo razdvojis funkcionalnosti. Npr. u auth servisu imas metodu za resetovanje lozinke u kojoj radis sledece stvari:
1. Proveravas da li user postoji
2. Hesiras
3. Saljes mail

Imas na vise mesta neke funkcije koje rade vise razlicitih stvari. Ja bi takve funkcije razbio na vise manjih. Npr. za slanje mejla bi kreirao neki emailservice koji bi imao metode vezane za mail. Onda imas na vise mesta gde proveravas da li user postoji. Napravi jednu metodu koja proverava da li postoji i onda na svim mestim samo pozvias tu metodu. To je to za sada

2022-12-31 11:52 UTC, antonic901 commented on Final/backend/routes/user.route.ts
> +router.patch("/updateMyPassword", authController.updateMyPassword);
Rute bi trebale da imaju - umesto velikih slova. Umesto updateMyPassword da bude update-my-password. Takodje, nema potrebe da u nazivu rute pises sta ona radi. Ako uradis router.get(/password) podrazumeva se da hoces da ga dobavis. Ako uradis router.post(/password) podrazumeva se da hoces da ga dodas. Ako uradis router.patch(/password) podrazumeva se da hoces da apdejtujes password.

2022-12-31 11:52 UTC, antonic901 commented on Final/backend/services/auth.service.ts
> +};
AuthService bi trebao da ima samo logiku da dobavi user-a na osnovu nekog obelezja (npr. username-a ili email-a). Request objekat nikada ne prosledjujemo servisu. Sva ova logika oko izvlacenja jwt tokena iz request-a, pa iz jwt tokena username itd. treba da se napise u nekoj middleware funkciji. Npr. napravis folder midlewares i u njemu auth.midleware.ts i iz tih funkcija pozivas basicne funkcije iz auth.service.ts

2023-01-19 11:30 UTC, antonic901 requested changes

2023-01-21 14:45 UTC, merged